USE baseballbdd;

ALTER TABLE plaTea DROP CONSTRAINT platea_ibfk_1;
ALTER TABLE plaTea DROP CONSTRAINT platea_ibfk_2;

DROP TABLE IF EXISTS players;
CREATE TABLE players(
    idPla INT UNSIGNED NOT NULL AUTO_INCREMENT,
    firstName VARCHAR(128) NOT NULL,
    lastName VARCHAR(128) NOT NULL,
    num INT(5) NOT NULL,
    position VARCHAR(128) NOT NULL,
    PRIMARY KEY(idPla)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS teams;
CREATE TABLE teams(
    idTea INT UNSIGNED NOT NULL AUTO_INCREMENT,
    zoneTeam VARCHAR(128) NOT NULL,
    libTeam VARCHAR(128) NOT NULL,
    PRIMARY KEY(idTea)
) Engine=InnoDB;

DROP TABLE IF EXISTS plaTea;
CREATE TABLE plaTea(
    idPla INT UNSIGNED NOT NULL,
    idTea INT UNSIGNED NOT NULL,
    PRIMARY KEY(idPla, idTea),
    FOREIGN KEY(idPla) REFERENCES players(idPla),
    FOREIGN KEY(idTea) REFERENCES teams(idTea)
) Engine=InnoDB;

